from rest_framework import serializers
from shared.models.core.company import Company

class CompanySerializer(serializers.ModelSerializer):
    class Meta:
        model = Company
        fields = [
            'id',
            'company_name',
            'company_code',
            'company_type',
            'logo',
            'established_date',
            'about_company',
            'client_name',
            'client_designation',
            'country_number_code',
            'client_number',
            'client_email',
            'client_gender',
            'website',
            'address_line_1',
            'address_line_2',
            'country',
            'state',
            'city',
            'pincode',
            'no_of_floors',
            'no_of_blocks',
            'no_of_rooms',
            'special_features',
            'allow_plan_renewal_on_same_price',
            'bill_me',
            'plan_type',
            'adds_on_services',
            'plan_activation_date',
            'subscription_end_date',
            'no_of_users',
            'no_of_employees',
            'payment_mode',
            'payment_status',
            'amount_paid',
            'sub_domain',
            'timezone',
        ]

class CompanyListSerializer(serializers.ModelSerializer):
    class Meta:
        model = Company
        fields = [
            'id',
            'company_name',
            'company_code',
            'company_type',
            'logo',
            'established_date',
            'about_company',
            'client_name',
            'client_designation',
            'country_number_code',
            'client_number',
            'client_email',
            'client_gender',
            'website',
            'address_line_1',
            'address_line_2',
            'country',
            'state',
            'city',
            'pincode',
            'no_of_floors',
            'no_of_blocks',
            'no_of_rooms',
            'special_features',
            'allow_plan_renewal_on_same_price',
            'bill_me',
            'plan_type',
            'adds_on_services',
            'plan_activation_date',
            'subscription_end_date',
            'no_of_users',
            'no_of_employees',
            'payment_mode',
            'payment_status',
            'amount_paid',
            'sub_domain',
            'timezone',
            'created_at',
            'updated_at',
            'deleted_at',
        ]        